name: clusterlib
main: org.clustermc.lib.ClusterLib
version: 1.0
author: Ktar5
commands:
  rank:
  ban:
  unban:
  mute:
  unmute:
  tmute:
  tban:
  kick:
  warn:
  eco:
  whisper:
    aliases: [whisper, tell, t, w, msg, m, r, re, reply, message]
  channel:
    aliases: [channel, c, chat, ch, chan]